# Site
repository: Mauricio Villagran resume
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Mauricio Villagran
title: Sr. Cloud Engineer
email: maurivg25@gmail.com
email_title: Email
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://blog.mauriciovillagran.uy
website_title: Web

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: Mauricio Villagran Garcia

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: /images/Perfil.jpg
about_content: | # this will include new lines to allow paragraphs
  Mauricio, has more than 10 years of experience working in IT. He has participated and led different migration projects (Applications, Mail Systems, Hybrid Clouds, etc). handling all kinds of technologies. He has strong knowledge of Microsoft technologies (AD, SQL, Azure, SharePoint, Office 365, Azure, etc); and Virtualization technologies (VmWare, HyperV, etc). Currently, he was participating in migration projects of payment means applications to Azure, using DevOps methodologies and tools such as Ansible, Terraform and Azure DevOps. He also has knowledge of kubernetes and orchestrators (Rancher, OKD, etc.); and has also participated in the implementation of these technologies.

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       border: weak  # Value of `weak` will display a weak border below this item. # Any 
  #                     # other value (or no value) means no border will be displayed
  #       title: Blue green deployment
  #       # link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       # link_text: Link Text
  #       # additional_links:
  #       #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #       #     icon: fab fa-github
  #       #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #       #     icon: fab fa-github
  #       #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       quote: >
  #         Amazon ECS blue green deployment
  #       description: | # this will include new lines to allow paragraphs
  #         Creation of two ECS clusters in two different regions using terraform to deploy all its infrastructure.
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Globant
        sub_title: Sr. Cloud Engineer
        caption: August 2021 - present
        link: https://globant.com
        quote: 
        description: | # this will include new lines to allow paragraphs
          **Description of role:**
          - Multi-region infrastructure management on AWS.
          - Development of infrastructure as code using Terraform.
          - Migrating from ECS to EKS.
          - Use of CI/CD tools such as Harness and Gitlab.
          - EKS administration.
          - Technical lead.
      - layout: right
        title: Pyxis
        sub_title: Sr. System Administrator
        caption: March 2014 - August 2021
        link: https://pyxis.com.uy
        quote: 
        description: | # this will include new lines to allow paragraphs
          **Description of role:**
          - Architecture design for payment application migration developed in .net to Azure. Infrastructure development as code (Using, Terraform, and Ansible for configuration), and implementation of it through CI / CD process with Azure DevOps.
          - Support to development teams to implement the application code under CI / CD, using Azure DevOps.
          - Implementation of different Azure solutions. (For example, WVD, Azure SQL, etc).
          - Implementation of different kubernetes orchestrators. (For example, OKD and Rancher).
          - Infrastructure provision as a service (IaaS) using Devops tools.
          - Platform as a service (PaaS) provisioning using Devops tools.
          - Administration, design, infrastructure and systems support.
          - Database installation, configuration and administration.
          - Migration of on premises Microsoft Exchange Servers to Office365.
          - Migration of Microsoft Exchange Servers to new versions.
          - Migration of different Microsoft Technologies, such as (Active Directory, SQL Server, IIS, SharePoint, System Center, etc.).
      - layout: right
        title: Arnaldo Castro
        sub_title: Sr. System Administrator
        caption: May 2010 - January 2014
        link: https://arnaldocastro.com.uy
        quote: 
        description: | # this will include new lines to allow paragraphs
          **Description of role:**
          - Migration, Installation, configuration, and administration of virtualization systems (VMWare).
          - Migration, Installation, and configuration of systems (Microsoft).
          - Configuration, administration and resolution of network problems.
          - Development of automatic tasks with scritpting using Bash, and PowerShell.
          - Installation, configuration and administration of monitoring and reporting tools.
          - Installation, configuration and administration of OpenSource systems for company branches.
          - Deployment, configuration and administration of services such as Squid, Apache, DNS, Postfix.
          - Installation, configuration and administration of backup tools, for both Virtual and OnPremise infrastructure.
      - layout: right
        title: IDS Ltda
        sub_title: Support Engineer
        caption: October 2008 - May 2010
        link: https://www.idsltda.uy
        quote: 
        description: | # this will include new lines to allow paragraphs
          **Description of role:**
          - Level 1 on site and remote support for different clients using Microsoft and Linux technologies.
          - Network troubleshooting.
          - Linux server administration (OpenSuse).
      - layout: right
        title: GHM Uruguay
        sub_title: Technician
        caption: January 2008 - March 2008
        link: 
        quote: 
        description: | # this will include new lines to allow paragraphs
          **Description of role:**
          - Assembling and repairing computers.
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Solymar High School
        sub_title: Bachelor Degree.
        caption: 1997 - 2004.
        quote: >
          At the Solymar high school I continued my studies in the scientific orientation and then in the engineering orientation.
        description: | # this will include new lines to allow paragraphs
          I have received a bachelor's degree in engineering orientation.
  - title: Certifications
    layout: list
    content:
      - layout: top-right
        title: Azure administrator
        sub_title: Microsoft Certification.
        caption: 2017
        # quote: >
        description: | # this will include new lines to allow paragraphs
          - MCSE: Implementing Microsoft Azure Infrastructure Solutions.
          - MCSE: Cloud Platform and Infrastructure.
      - layout: top-right
        title: Sharepoint Server
        sub_title: Microsoft Certification.
        caption: 2014
        # quote: >
        description: | # this will include new lines to allow paragraphs
          - MCSE Core Solutions of Microsoft SharePoint Server 2013.
      - layout: top-right
        title: Windows Server 2012
        sub_title: Microsoft Certification.
        caption: 2013
        # quote: >
        description: | # this will include new lines to allow paragraphs
          - MCSA-MCSE: Installing and Configuring Windows Server 2012.
          - MCSA-MCSE: Administering Windows Server 2012.
          - MCSA - MCSE: Configuring Advanced Windows Server 2012 Services.
      - layout: top-right
        title: Microsoft Dynamics CRM 2011
        sub_title: Microsoft Certification.
        caption: 2012
        # quote: >
        description: | # this will include new lines to allow paragraphs
          - MCTS: Microsoft Dynamics CRM 2011 Installation and Configuration.
      - layout: top-right
        title: Exchange 2010
        sub_title: Microsoft Certification.
        caption: 2012
        # quote: >
        description: | # this will include new lines to allow paragraphs
          - MCTS: Configuring Microsoft Exchange Server 2010.
  - title: Courses
    layout: list
    content:
      - layout: top-right
        title: CKA Certification
        sub_title: Udemy CKA Kubernetes Administrator.
        caption: 2017
        # quote: >
        description: | # this will include new lines to allow paragraphs
          I took the Kubernetes administration course, which had 22 theoretical hours, plus labs and mock exams.
      - layout: top-right
        title: Linux Administration
        sub_title: Linux Administrator.
        caption: 2009
        # quote: >
        description: | # this will include new lines to allow paragraphs
          I took a linux administration course based on OpenSuse.
  - title: Summary of Qualifications
    layout: text
    content: | # this will include new lines to allow paragraphs
      **Proficient In:**

        | Gitlab  | AWS  | Microsoft Technologies  | Virtualization Technologies  | Azure Cloud  |
        | Azure DevOps | Jenkins | Kubernetes | Docker | Git repositories |
        | Ansible | Terraform | Powershell | PowerShell DSC | Harness |
        | Istio | CloudTruth | CI/CD | Bash | NodeJs Scripts |
        | Responsible | Resilience | Committed | Teamwork | Leadership|

# Footer
footer_show_references: true
references_title: Copyright 2023

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
