# Site
repository: Mauricio Villagran resume
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Mauricio Villagran
title: Sr. Cloud Engineer
# email: Your email (optional)
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://blog.mauriciovillagran.uy
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
linkedin_username: https://uy.linkedin.com/in/mauricio-villagr%C3%A1n-garc%C3%ADa-43a54b25

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  Mauricio, has more than 10 years of experience working in IT. He has participated and led different migration projects (Applications, Mail Systems, Hybrid Clouds, etc). handling all kinds of technologies. He has strong knowledge of Microsoft technologies (AD, SQL, Azure, SharePoint, Office 365, Azure, etc); and Virtualization technologies (VmWare, HyperV, etc). Currently, he was participating in migration projects of payment means applications to Azure, using DevOps methodologies and tools such as Ansible, Terraform and Azure DevOps. He also has knowledge of kubernetes and orchestrators (Rancher, OKD, etc.); and has also participated in the implementation of these technologies.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Blue green deployment
        # link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # link_text: Link Text
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Amazon ECS blue green deployment
        description: | # this will include new lines to allow paragraphs
          Creation of two ECS clusters in two different regions using terraform to deploy all its infrastructure.
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Company name
        sub_title: Job title
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Description of role
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Institution name
        sub_title: Qualifications (eg. BA Performing Arts)
        caption: Date Range (eg. 2016 - 2019)
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification
  - title: Summary of Qualifications
    layout: text
    content: | # this will include new lines to allow paragraphs
      Proficient In:
        - Gitlab
        - AWS
        - Microsoft Technologies
        - Virtualization Technologies
        - Azure Cloud
        - Azure DevOps
        - Jenkins
        - Kubernetes
        - Docker
        - Git repositories
        - Ansible
        - Terraform
        - Powershell
        - PowerShell DSC
        - Responsible
        - Resilience
        - Committed
        - Teamwork
        - Leadership


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
